#!/bin/sh
export XDG_RUNTIME_DIR=/tmp/xdg-runtime-$(id -u)
mkdir -p $XDG_RUNTIME_DIR
chmod 0700 $XDG_RUNTIME_DIR

export QT_SCALE_FACTOR=1
export GBM_BACKEND=nvidia-drm
export LIBVA_DRIVER_NAME=nvidia
export __GLX_VENDOR_LIBRARY_NAME=nvidia
export QT_QPA_PLATFORM=wayland
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export XDG_SESSION_TYPE=wayland
export MOZ_ENABLE_WAYLAND=1
export GDK_BACKEND=wayland 
export WLR_NO_HARDWARE_CURSORS=1
export XDG_CURRENT_DESKTOP=wlr
export XDG_SESSION_DESKTOP=wlr
export SDL_VIDEODRIVER=wayland
export CLUTTER_BACKEND=wayland
export ELECTRON_OZONE_PLATFORM_HINT=auto
export EDITOR=nvim
export SUDO=doas

export __GL_THREADED_OPTIMIZATIONS=0

gpg-connect-agent updatestartuptty /bye >/dev/null
unset SSH_AGENT_PID
if [ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]; then
  export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
fi

mkfifo $XDG_RUNTIME_DIR/statuspipe
someblocks -p > $XDG_RUNTIME_DIR/statuspipe &
dbus-run-session dwl -s 'pipewire &  
        pipewire-pulse &
        wireplumber &
        swaybg -i /mnt/ssd/papes/thiemeyer_road_to_samarkand.jpg & 
        wlr-randr --output DP-3 --mode 2560x1440@239.998001
        wlr-randr --output DP-2 --mode 2560x1440@165
        $HOME/.config/dwl/portal &
        mako &
' < $XDG_RUNTIME_DIR/statuspipe
rm $XDG_RUNTIME_DIR/statuspipe
